import { Nunito } from 'next/font/google'
import './globals.css'

const nunito = Nunito({
  weight:['600', '700'],
  subsets: ['latin-ext'],
  variable: '--font-nunito'
})
export const metadata = {
  title: 'Level Up',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunito.className}`}>
        <nav>
          <h1>Logo</h1>
          <ul>
          <li>
            <a href="/">Home</a>
          </li>
          <li>
            <a href="/about">About</a>
          </li>
          <li>
            <a href="/info">Info</a>
          </li>
          </ul>
        </nav>
        {children}</body>
    </html>
  )
}
